### ISSUE TITLE
Run the evaluate_vp.py problem

### ISSUE THREAD

**Issue by Kimbo-Chang** [fkluger/consac#2]
1. I can't use the Gpu run evaluate_vp.py when i modift the --visualise default=True. Onle use cpu can run.
![image](https://user-images.githubusercontent.com/53865482/82144941-31f82700-987a-11ea-960a-81ee02c5ff44.png)

3. If I hope using the ransca network to run some picture, the picture like this paper Figure 4. What should i do?

**Comment by fkluger** [comment]
1. Fixed with the latest commit.
2. I'm not sure what you mean. For homography estimation, the demo.py script does basically just that. For other problems, you'd have to modify the code accordingly. Feel free to ask if you have more specific questions.
