### ISSUE TITLE
vanishing point detection on a new image

### ISSUE THREAD

**Issue by yanconglin** [fkluger/consac#3]
Hi,Florian 

Nice work!
Could you please provide a new script to do vanishing point detection on a new image or a new dataset? 
Thanks a lot!

Kind regards,
Yancong

**Comment by fkluger** [comment]
Hey Yancong,
thanks a lot! I just added a vanishing point detection demo, which you can also apply to your own images. Check out the README, ```python demo.py --help``` and of course the source code, and let me know if there are any problems.
Cheers,
Florian
