### ISSUE TITLE
cannot run homography evaluation code

### ISSUE THREAD

**Issue by xue-zzx-zhang** [fkluger/consac#6]
I used "python evaluate_homography.py --dataset_path PATH_TO_AdelaideRMF --runcount 5" to run homography evaluation, but get the following error message, could you help? Thanks!
![Capture](https://user-images.githubusercontent.com/100447049/166090711-98412ef2-52ea-45e3-8c98-00ef0336eb6a.JPG)

**Comment by fkluger** [comment]
Hi,

I am not sure what exactly is going on there, but the error seems to come from the data loader. Did you replace `PATH_TO_AdelaideRMF` in the command with the actual path to the dataset?

**Comment by xue-zzx-zhang** [comment]
Yes, I did. I downloaded the mirror from the link that you provided, and I unzip it to consac\adelaidermf. So the command that I used was "python evaluate_homography.py --dataset_path ./adelaidermf". Did I miss anything? Thanks!

**Comment by xue-zzx-zhang** [comment]
Are you running the code in Linux or Windows environment? Thanks!
