### ISSUE TITLE
Troubles when running homography training code

### ISSUE THREAD

**Issue by xue-zzx-zhang** [fkluger/consac#8]
Hi, I was trying to run the homography training code, and I used the command "python train_homography.py --calr --fair_sampling". I did not assign GPU ID, but I got the following errors. Did I miss anything? Could you please help? Thanks!

![Capture](https://user-images.githubusercontent.com/100447049/172966814-2982157a-347b-464f-b967-ab3eacc4c39e.JPG)

**Comment by fkluger** [comment]
Hi, I get the same error when the training data is not at the correct location.

Please carefully follow the steps described in the README:
https://github.com/fkluger/consac#sfm-data
